// Auto-generated from the canonical PGP word list (magic-wormhole transcription).
// Source: https://raw.githubusercontent.com/warner/magic-wormhole/master/src/wormhole/_wordlist.py
// 256 even-position words (two syllables) and 256 odd-position words (three syllables),
// indexed by byte value 0x00..0xFF. `all` is the 512-word union for Twilio <Gather hints>.

export const EVEN_WORDS: readonly string[] = [
  "aardvark", "absurd", "accrue", "acme", "adrift", "adult", "afflict", "ahead",
  "aimless", "Algol", "allow", "alone", "ammo", "ancient", "apple", "artist",
  "assume", "Athens", "atlas", "Aztec", "baboon", "backfield", "backward", "banjo",
  "beaming", "bedlamp", "beehive", "beeswax", "befriend", "Belfast", "berserk", "billiard",
  "bison", "blackjack", "blockade", "blowtorch", "bluebird", "bombast", "bookshelf", "brackish",
  "breadline", "breakup", "brickyard", "briefcase", "Burbank", "button", "buzzard", "cement",
  "chairlift", "chatter", "checkup", "chisel", "choking", "chopper", "Christmas", "clamshell",
  "classic", "classroom", "cleanup", "clockwork", "cobra", "commence", "concert", "cowbell",
  "crackdown", "cranky", "crowfoot", "crucial", "crumpled", "crusade", "cubic", "dashboard",
  "deadbolt", "deckhand", "dogsled", "dragnet", "drainage", "dreadful", "drifter", "dropper",
  "drumbeat", "drunken", "Dupont", "dwelling", "eating", "edict", "egghead", "eightball",
  "endorse", "endow", "enlist", "erase", "escape", "exceed", "eyeglass", "eyetooth",
  "facial", "fallout", "flagpole", "flatfoot", "flytrap", "fracture", "framework", "freedom",
  "frighten", "gazelle", "Geiger", "glitter", "glucose", "goggles", "goldfish", "gremlin",
  "guidance", "hamlet", "highchair", "hockey", "indoors", "indulge", "inverse", "involve",
  "island", "jawbone", "keyboard", "kickoff", "kiwi", "klaxon", "locale", "lockup",
  "merit", "minnow", "miser", "Mohawk", "mural", "music", "necklace", "Neptune",
  "newborn", "nightbird", "Oakland", "obtuse", "offload", "optic", "orca", "payday",
  "peachy", "pheasant", "physique", "playhouse", "Pluto", "preclude", "prefer", "preshrunk",
  "printer", "prowler", "pupil", "puppy", "python", "quadrant", "quiver", "quota",
  "ragtime", "ratchet", "rebirth", "reform", "regain", "reindeer", "rematch", "repay",
  "retouch", "revenge", "reward", "rhythm", "ribcage", "ringbolt", "robust", "rocker",
  "ruffled", "sailboat", "sawdust", "scallion", "scenic", "scorecard", "Scotland", "seabird",
  "select", "sentence", "shadow", "shamrock", "showgirl", "skullcap", "skydive", "slingshot",
  "slowdown", "snapline", "snapshot", "snowcap", "snowslide", "solo", "southward", "soybean",
  "spaniel", "spearhead", "spellbind", "spheroid", "spigot", "spindle", "spyglass", "stagehand",
  "stagnate", "stairway", "standard", "stapler", "steamship", "sterling", "stockman", "stopwatch",
  "stormy", "sugar", "surmount", "suspense", "sweatband", "swelter", "tactics", "talon",
  "tapeworm", "tempest", "tiger", "tissue", "tonic", "topmost", "tracker", "transit",
  "trauma", "treadmill", "Trojan", "trouble", "tumor", "tunnel", "tycoon", "uncut",
  "unearth", "unwind", "uproot", "upset", "upshot", "vapor", "village", "virus",
  "Vulcan", "waffle", "wallet", "watchword", "wayside", "willow", "woodlark", "Zulu",
];

export const ODD_WORDS: readonly string[] = [
  "adroitness", "adviser", "aftermath", "aggregate", "alkali", "almighty", "amulet", "amusement",
  "antenna", "applicant", "Apollo", "armistice", "article", "asteroid", "Atlantic", "atmosphere",
  "autopsy", "Babylon", "backwater", "barbecue", "belowground", "bifocals", "bodyguard", "bookseller",
  "borderline", "bottomless", "Bradbury", "bravado", "Brazilian", "breakaway", "Burlington", "businessman",
  "butterfat", "Camelot", "candidate", "cannonball", "Capricorn", "caravan", "caretaker", "celebrate",
  "cellulose", "certify", "chambermaid", "Cherokee", "Chicago", "clergyman", "coherence", "combustion",
  "commando", "company", "component", "concurrent", "confidence", "conformist", "congregate", "consensus",
  "consulting", "corporate", "corrosion", "councilman", "crossover", "crucifix", "cumbersome", "customer",
  "Dakota", "decadence", "December", "decimal", "designing", "detector", "detergent", "determine",
  "dictator", "dinosaur", "direction", "disable", "disbelief", "disruptive", "distortion", "document",
  "embezzle", "enchanting", "enrollment", "enterprise", "equation", "equipment", "escapade", "Eskimo",
  "everyday", "examine", "existence", "exodus", "fascinate", "filament", "finicky", "forever",
  "fortitude", "frequency", "gadgetry", "Galveston", "getaway", "glossary", "gossamer", "graduate",
  "gravity", "guitarist", "hamburger", "Hamilton", "handiwork", "hazardous", "headwaters", "hemisphere",
  "hesitate", "hideaway", "holiness", "hurricane", "hydraulic", "impartial", "impetus", "inception",
  "indigo", "inertia", "infancy", "inferno", "informant", "insincere", "insurgent", "integrate",
  "intention", "inventive", "Istanbul", "Jamaica", "Jupiter", "leprosy", "letterhead", "liberty",
  "maritime", "matchmaker", "maverick", "Medusa", "megaton", "microscope", "microwave", "midsummer",
  "millionaire", "miracle", "misnomer", "molasses", "molecule", "Montana", "monument", "mosquito",
  "narrative", "nebula", "newsletter", "Norwegian", "October", "Ohio", "onlooker", "opulent",
  "Orlando", "outfielder", "Pacific", "pandemic", "Pandora", "paperweight", "paragon", "paragraph",
  "paramount", "passenger", "pedigree", "Pegasus", "penetrate", "perceptive", "performance", "pharmacy",
  "phonetic", "photograph", "pioneer", "pocketful", "politeness", "positive", "potato", "processor",
  "provincial", "proximate", "puberty", "publisher", "pyramid", "quantity", "racketeer", "rebellion",
  "recipe", "recover", "repellent", "replica", "reproduce", "resistor", "responsive", "retraction",
  "retrieval", "retrospect", "revenue", "revival", "revolver", "sandalwood", "sardonic", "Saturday",
  "savagery", "scavenger", "sensation", "sociable", "souvenir", "specialist", "speculate", "stethoscope",
  "stupendous", "supportive", "surrender", "suspicious", "sympathy", "tambourine", "telephone", "therapist",
  "tobacco", "tolerance", "tomorrow", "torpedo", "tradition", "travesty", "trombonist", "truncated",
  "typewriter", "ultimate", "undaunted", "underfoot", "unicorn", "unify", "universe", "unravel",
  "upcoming", "vacancy", "vagabond", "vertigo", "Virginia", "visitor", "vocalist", "voyager",
  "warranty", "Waterloo", "whimsical", "Wichita", "Wilmington", "Wyoming", "yesteryear", "Yucatan",
];

export const ALL_WORDS: readonly string[] = [
  "Algol", "Apollo", "Athens", "Atlantic", "Aztec", "Babylon", "Belfast", "Bradbury",
  "Brazilian", "Burbank", "Burlington", "Camelot", "Capricorn", "Cherokee", "Chicago", "Christmas",
  "Dakota", "December", "Dupont", "Eskimo", "Galveston", "Geiger", "Hamilton", "Istanbul",
  "Jamaica", "Jupiter", "Medusa", "Mohawk", "Montana", "Neptune", "Norwegian", "Oakland",
  "October", "Ohio", "Orlando", "Pacific", "Pandora", "Pegasus", "Pluto", "Saturday",
  "Scotland", "Trojan", "Virginia", "Vulcan", "Waterloo", "Wichita", "Wilmington", "Wyoming",
  "Yucatan", "Zulu", "aardvark", "absurd", "accrue", "acme", "adrift", "adroitness",
  "adult", "adviser", "afflict", "aftermath", "aggregate", "ahead", "aimless", "alkali",
  "allow", "almighty", "alone", "ammo", "amulet", "amusement", "ancient", "antenna",
  "apple", "applicant", "armistice", "article", "artist", "assume", "asteroid", "atlas",
  "atmosphere", "autopsy", "baboon", "backfield", "backward", "backwater", "banjo", "barbecue",
  "beaming", "bedlamp", "beehive", "beeswax", "befriend", "belowground", "berserk", "bifocals",
  "billiard", "bison", "blackjack", "blockade", "blowtorch", "bluebird", "bodyguard", "bombast",
  "bookseller", "bookshelf", "borderline", "bottomless", "brackish", "bravado", "breadline", "breakaway",
  "breakup", "brickyard", "briefcase", "businessman", "butterfat", "button", "buzzard", "candidate",
  "cannonball", "caravan", "caretaker", "celebrate", "cellulose", "cement", "certify", "chairlift",
  "chambermaid", "chatter", "checkup", "chisel", "choking", "chopper", "clamshell", "classic",
  "classroom", "cleanup", "clergyman", "clockwork", "cobra", "coherence", "combustion", "commando",
  "commence", "company", "component", "concert", "concurrent", "confidence", "conformist", "congregate",
  "consensus", "consulting", "corporate", "corrosion", "councilman", "cowbell", "crackdown", "cranky",
  "crossover", "crowfoot", "crucial", "crucifix", "crumpled", "crusade", "cubic", "cumbersome",
  "customer", "dashboard", "deadbolt", "decadence", "decimal", "deckhand", "designing", "detector",
  "detergent", "determine", "dictator", "dinosaur", "direction", "disable", "disbelief", "disruptive",
  "distortion", "document", "dogsled", "dragnet", "drainage", "dreadful", "drifter", "dropper",
  "drumbeat", "drunken", "dwelling", "eating", "edict", "egghead", "eightball", "embezzle",
  "enchanting", "endorse", "endow", "enlist", "enrollment", "enterprise", "equation", "equipment",
  "erase", "escapade", "escape", "everyday", "examine", "exceed", "existence", "exodus",
  "eyeglass", "eyetooth", "facial", "fallout", "fascinate", "filament", "finicky", "flagpole",
  "flatfoot", "flytrap", "forever", "fortitude", "fracture", "framework", "freedom", "frequency",
  "frighten", "gadgetry", "gazelle", "getaway", "glitter", "glossary", "glucose", "goggles",
  "goldfish", "gossamer", "graduate", "gravity", "gremlin", "guidance", "guitarist", "hamburger",
  "hamlet", "handiwork", "hazardous", "headwaters", "hemisphere", "hesitate", "hideaway", "highchair",
  "hockey", "holiness", "hurricane", "hydraulic", "impartial", "impetus", "inception", "indigo",
  "indoors", "indulge", "inertia", "infancy", "inferno", "informant", "insincere", "insurgent",
  "integrate", "intention", "inventive", "inverse", "involve", "island", "jawbone", "keyboard",
  "kickoff", "kiwi", "klaxon", "leprosy", "letterhead", "liberty", "locale", "lockup",
  "maritime", "matchmaker", "maverick", "megaton", "merit", "microscope", "microwave", "midsummer",
  "millionaire", "minnow", "miracle", "miser", "misnomer", "molasses", "molecule", "monument",
  "mosquito", "mural", "music", "narrative", "nebula", "necklace", "newborn", "newsletter",
  "nightbird", "obtuse", "offload", "onlooker", "optic", "opulent", "orca", "outfielder",
  "pandemic", "paperweight", "paragon", "paragraph", "paramount", "passenger", "payday", "peachy",
  "pedigree", "penetrate", "perceptive", "performance", "pharmacy", "pheasant", "phonetic", "photograph",
  "physique", "pioneer", "playhouse", "pocketful", "politeness", "positive", "potato", "preclude",
  "prefer", "preshrunk", "printer", "processor", "provincial", "prowler", "proximate", "puberty",
  "publisher", "pupil", "puppy", "pyramid", "python", "quadrant", "quantity", "quiver",
  "quota", "racketeer", "ragtime", "ratchet", "rebellion", "rebirth", "recipe", "recover",
  "reform", "regain", "reindeer", "rematch", "repay", "repellent", "replica", "reproduce",
  "resistor", "responsive", "retouch", "retraction", "retrieval", "retrospect", "revenge", "revenue",
  "revival", "revolver", "reward", "rhythm", "ribcage", "ringbolt", "robust", "rocker",
  "ruffled", "sailboat", "sandalwood", "sardonic", "savagery", "sawdust", "scallion", "scavenger",
  "scenic", "scorecard", "seabird", "select", "sensation", "sentence", "shadow", "shamrock",
  "showgirl", "skullcap", "skydive", "slingshot", "slowdown", "snapline", "snapshot", "snowcap",
  "snowslide", "sociable", "solo", "southward", "souvenir", "soybean", "spaniel", "spearhead",
  "specialist", "speculate", "spellbind", "spheroid", "spigot", "spindle", "spyglass", "stagehand",
  "stagnate", "stairway", "standard", "stapler", "steamship", "sterling", "stethoscope", "stockman",
  "stopwatch", "stormy", "stupendous", "sugar", "supportive", "surmount", "surrender", "suspense",
  "suspicious", "sweatband", "swelter", "sympathy", "tactics", "talon", "tambourine", "tapeworm",
  "telephone", "tempest", "therapist", "tiger", "tissue", "tobacco", "tolerance", "tomorrow",
  "tonic", "topmost", "torpedo", "tracker", "tradition", "transit", "trauma", "travesty",
  "treadmill", "trombonist", "trouble", "truncated", "tumor", "tunnel", "tycoon", "typewriter",
  "ultimate", "uncut", "undaunted", "underfoot", "unearth", "unicorn", "unify", "universe",
  "unravel", "unwind", "upcoming", "uproot", "upset", "upshot", "vacancy", "vagabond",
  "vapor", "vertigo", "village", "virus", "visitor", "vocalist", "voyager", "waffle",
  "wallet", "warranty", "watchword", "wayside", "whimsical", "willow", "woodlark", "yesteryear",
];

// Encode 3 bytes as 3 PGP words: positions 0,2 use EVEN; position 1 uses ODD.
export function bytesToWords(b0: number, b1: number, b2: number): [string, string, string] {
  return [EVEN_WORDS[b0 & 0xff], ODD_WORDS[b1 & 0xff], EVEN_WORDS[b2 & 0xff]];
}
